nodeLinker: node-modules
plugins:
  - .yarn/plugins/linker.cjs
packageExtensions:
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  "@typescript-eslint/experimental-utils@*":
    peerDependencies:
      typescript: "*"
  "@vector-im/compound-web@*":
    peerDependencies:
      react-dom: "*"
  "eslint-plugin-jest@*":
    peerDependencies:
      typescript: "*"
