name: Backend quality checks
on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  backend:
    name: Backend quality checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: "pnpm"
          cache-dependency-path: backend/pnpm-lock.yaml
          node-version-file: backend/.node-version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm lint:types
      - name: Test
        run: pnpm test --runInBand
      - name: Build
        run: pnpm build
