name: Frontend quality checks
on:
  workflow_dispatch: {}
jobs:
  frontend:
    name: Frontend quality checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock
          node-version-file: "frontend/.node-version"
      - name: Install dependencies
        run: "corepack yarn install --immutable"
      - name: Prettier
        run: "corepack yarn prettier:check"
      - name: i18n
        run: "corepack yarn i18n:check"
      - name: ESLint
        run: "corepack yarn lint:eslint"
      - name: Type check
        run: "corepack yarn lint:types"
      - name: Unit tests
        run: "corepack yarn test --run"
      - name: Dead code analysis
        run: "corepack yarn lint:knip"
